title: Debadatta Mohapatra # your name (or website title) here
logo: "/deba.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data Architect/Engineer
  <br><br>
  <a href="mailto:debadatta.moha@gmail.com">debadatta.moha@gmail.com </a>
  <br><br>
  <a href="https://aws.amazon.com/blogs/big-data/how-epos-now-modernized-their-data-platform-by-building-an-end-to-end-data-lake-with-the-aws-data-lab/">Sample Reference Architetcure</a> 
 <br><br>
theme: jekyll-theme-minimal